### ISSUE TITLE
makeEffectiveArea seg fault while running prod3b QC

### ISSUE THREAD

**Issue by GernotMaier** [Eventdisplay/Eventdisplay#10]
Error messages:

`VSpectralWeight: expect input (MC) energy spectra with index 2 in energy range [0.003, 330] TeV

VEffectiveAreaCalculator::getMonteCarloSpectra: solid angle normalization factor: 0.0701334
	 total number of data events: 3927468 (start at event 0)

 *** Break *** segmentation violation

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007fee3f28b45c in waitpid () from /lib64/libc.so.6
#1  0x00007fee3f208f52 in do_system () from /lib64/libc.so.6
#2  0x00007fee44e5ff44 in TUnixSystem::StackTrace (this=0xb57700) at /afs/ifh.de/group/cta/cta/software/root/root-6.18.02/core/unix/src/TUnixSystem.cxx:2400
#3  0x00007fee44e6267c in TUnixSystem::DispatchSignals (this=0xb57700, sig=kSigSegmentationViolation) at /afs/ifh.de/group/cta/cta/software/root/root-6.18.02/core/unix/src/TUnixSystem.cxx:3631
#4  <signal handler called>
#5  0x0000000000474839 in VEffectiveAreaCalculator::fillAngularResolution (this=this
entry=0x7ffe8d3d5570, i_az=i_az
entry=0, iContainment_80p=iContainment_80p
entry=false) at src/VEffectiveAreaCalculator.cpp:3552
#6  0x0000000000488d03 in VEffectiveAreaCalculator::fill (this=this
entry=0x7ffe8d3d5570, d=d
entry=0x7ffe8d3e9740, iMC_histo=iMC_histo
entry=0x4ce9620, iMethod=<optimized out>) at src/VEffectiveAreaCalculator.cpp:2149
#7  0x0000000000452427 in main (argc=<optimized out>, argv=<optimized out>) at src/makeEffectiveArea.cpp:391
===========================================================

The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x0000000000474839 in VEffectiveAreaCalculator::fillAngularResolution (this=this
entry=0x7ffe8d3d5570, i_az=i_az
entry=0, iContainment_80p=iContainment_80p
entry=false) at src/VEffectiveAreaCalculator.cpp:3552
#6  0x0000000000488d03 in VEffectiveAreaCalculator::fill (this=this
entry=0x7ffe8d3d5570, d=d
entry=0x7ffe8d3e9740, iMC_histo=iMC_histo
entry=0x4ce9620, iMethod=<optimized out>) at src/VEffectiveAreaCalculator.cpp:2149
#7  0x0000000000452427 in main (argc=<optimized out>, argv=<optimized out>) at src/makeEffectiveArea.cpp:391
===========================================================

`

**Comment by GernotMaier** [comment]
fixed with commit https://github.com/Eventdisplay/Eventdisplay/commit/92f9608a807efd936a6369f24caf319df5bc7e96
